/**
 * CSS generation for Skeleton color utilities
 */

import type { ParsedUtility, PropertyTarget } from './types.js';

/**
 * Get the CSS property name for a utility prefix
 */
export function getCSSProperty(property: PropertyTarget): string {
  const map: Record<PropertyTarget, string> = {
    bg: 'background-color',
    text: 'color',
    border: 'border-color',
    divide: 'border-color',
    ring: '--tw-ring-color',
    placeholder: 'color'
  };
  return map[property];
}

/**
 * Escape special characters for CSS class selectors
 */
export function escapeClassName(className: string): string {
  return className.replace(/[/:]/g, '\\$&');
}

/**
 * Generate CSS for a single utility class using EXPLICIT light/dark selectors
 *
 * This approach is more reliable than light-dark() because:
 * 1. Works in all browsers (light-dark() requires Chrome 123+, Safari 17.5+)
 * 2. Uses Tailwind's .dark class pattern for consistent behavior
 * 3. Avoids CSS cascade issues with @theme inline processing
 */
export function generatePairingCSS(parsed: ParsedUtility): string {
  const cssProperty = getCSSProperty(parsed.property);
  const escapedClass = escapeClassName(parsed.className);
  const lightVar = `--color-${parsed.scale}-${parsed.lightShade}`;
  const darkVar = `--color-${parsed.scale}-${parsed.darkShade}`;

  let css = '';

  // Special handling for placeholder pseudo-element
  if (parsed.property === 'placeholder') {
    if (parsed.hasOpacity) {
      css += `.${escapedClass}::placeholder {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
.dark .${escapedClass}::placeholder {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
    } else {
      css += `.${escapedClass}::placeholder {
  ${cssProperty}: var(${lightVar});
}
.dark .${escapedClass}::placeholder {
  ${cssProperty}: var(${darkVar});
}
`;
    }
    return css;
  }

  // Special handling for divide (targets children)
  if (parsed.property === 'divide') {
    if (parsed.hasOpacity) {
      css += `.${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
.dark .${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
    } else {
      css += `.${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: var(${lightVar});
}
.dark .${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: var(${darkVar});
}
`;
    }
    return css;
  }

  // Standard property - light mode (default)
  if (parsed.hasOpacity) {
    css += `.${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
.dark .${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
  } else {
    css += `.${escapedClass} {
  ${cssProperty}: var(${lightVar});
}
.dark .${escapedClass} {
  ${cssProperty}: var(${darkVar});
}
`;
  }

  return css;
}

/**
 * Generate CSS for a single utility class using separate light/dark selectors
 * (Alternative mode without pairing tokens)
 */
export function generateSeparateCSS(parsed: ParsedUtility, darkMode: boolean): string {
  const cssProperty = getCSSProperty(parsed.property);
  const lightVar = `--color-${parsed.scale}-${parsed.lightShade}`;
  const darkVar = `--color-${parsed.scale}-${parsed.darkShade}`;
  const escapedClass = escapeClassName(parsed.className);

  let css = '';

  // Light mode (default)
  if (parsed.hasOpacity) {
    css += `.${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
  } else {
    css += `.${escapedClass} {
  ${cssProperty}: var(${lightVar});
}
`;
  }

  // Dark mode variant
  if (darkMode) {
    if (parsed.hasOpacity) {
      css += `.dark .${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
    } else {
      css += `.dark .${escapedClass} {
  ${cssProperty}: var(${darkVar});
}
`;
    }
  }

  return css;
}

/**
 * Generate the complete CSS module content
 */
export function generateCSSModule(
  extractedClasses: Map<string, ParsedUtility>,
  usePairingTokens: boolean,
  darkMode: boolean
): string {
  let css = `/**
 * Skeleton Color Utilities - Auto-generated
 * Generated: ${new Date().toISOString()}
 * Classes: ${extractedClasses.size}
 *
 * This file is generated by @tinyland/vite-plugin-skeleton-colors.
 * It maps Tailwind-style utility classes (bg-surface-100-800) to
 * Skeleton v4.8 CSS custom properties (--color-surface-100-900).
 */

`;

  // Sort classes for consistent output
  const sortedClasses = [...extractedClasses.entries()].sort((a, b) =>
    a[0].localeCompare(b[0])
  );

  // Generate CSS for each extracted class
  for (const [, parsed] of sortedClasses) {
    if (usePairingTokens) {
      css += generatePairingCSS(parsed);
    } else {
      css += generateSeparateCSS(parsed, darkMode);
    }
    css += '\n';
  }

  return css;
}
